### ISSUE TITLE
Пример использования

### ISSUE THREAD

**Issue by memclutter** [burkostya/terraform-provider-vscale#3]
Как пользоваться данным провайдером? Можно пример?

**Comment by burkostya** [comment]
@vganyn добавил пример в своем MR https://github.com/burkostya/terraform-provider-vscale/pull/2/commits/bab97d7ef21cbd0a5c60f49f9e71759e06a5cc38

**Comment by urajio** [comment]
Вы планируете дальше развивать этот провайдер?

**Comment by burkostya** [comment]
@urajio В ближайшем будущем не планирую

**Comment by memclutter** [comment]
@burkostya спасибо!
